[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spatial_alert_prototype"
version = "0.0.1"

[tool.setuptools]
packages = ["backend", "ml_services", "data_simulation"]
